package backend.com.backend;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;

@EnableJpaAuditing
@SpringBootApplication
public class BackendApplication{

	public static void main(String[] args) {
		SpringApplication.run(BackendApplication.class, args);
	}

}
/*수만 Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJVU0VSIl0sInVzZXJuYW1lIjoic29vbWFuMzM0QGdtYWlsLmNvbSIsInN1YiI6InNvb21hbjMzNEBnbWFpbC5jb20iLCJpYXQiOjE2ODI0ODMwMzAsImV4cCI6MTY4MjQ4NDgzMH0.DODnlIhECAVoxAzcuJ02a89Qj9IfHviTVigAEpnI5OQ*/
/*아즈 Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJVU0VSIl0sInVzZXJuYW1lIjoidGxzNzg5QGdtYWlsLmNvbSIsInN1YiI6InRsczc4OUBnbWFpbC5jb20iLCJpYXQiOjE2ODI0ODMxMDMsImV4cCI6MTY4MjQ4NDkwM30.PSfV3Ma9v2DcOreTKTqAK9KN0UoJ36FXNXSNxXvGFKA*/